// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251127080257_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MaskineModul", b =>
                {
                    b.Property<string>("maskinerid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("modulerid")
                        .HasColumnType("varchar(255)");

                    b.HasKey("maskinerid", "modulerid");

                    b.HasIndex("modulerid");

                    b.ToTable("MaskineModul");
                });

            modelBuilder.Entity("WebApplication1.Models.Egenskab", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Egenskab");
                });

            modelBuilder.Entity("WebApplication1.Models.Fravaer", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("aarsag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("medarbejderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("medarbejderId");

                    b.ToTable("Fravaer");
                });

            modelBuilder.Entity("WebApplication1.Models.Maskine", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("egenskabId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("egenskabId");

                    b.ToTable("Maskine");
                });

            modelBuilder.Entity("WebApplication1.Models.Medarbejder", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Modulid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tlf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Modulid");

                    b.ToTable("Medarbejder");
                });

            modelBuilder.Entity("WebApplication1.Models.Modul", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("periodeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.HasIndex("periodeId");

                    b.ToTable("Modul");
                });

            modelBuilder.Entity("WebApplication1.Models.Nedetid", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Maskineid")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("dag")
                        .HasColumnType("int");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("gentagende")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeOnly>("tidspunkt")
                        .HasColumnType("time(6)");

                    b.HasKey("id");

                    b.HasIndex("Maskineid");

                    b.ToTable("Nedetid");
                });

            modelBuilder.Entity("WebApplication1.Models.Periode", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("end")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("Periode");
                });

            modelBuilder.Entity("WebApplication1.Models.Rolle", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("egenskabId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("medarbejderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("egenskabId");

                    b.HasIndex("medarbejderId");

                    b.ToTable("Rolle");
                });

            modelBuilder.Entity("MaskineModul", b =>
                {
                    b.HasOne("WebApplication1.Models.Maskine", null)
                        .WithMany()
                        .HasForeignKey("maskinerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Modul", null)
                        .WithMany()
                        .HasForeignKey("modulerid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Models.Fravaer", b =>
                {
                    b.HasOne("WebApplication1.Models.Medarbejder", "medarbejder")
                        .WithMany()
                        .HasForeignKey("medarbejderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("medarbejder");
                });

            modelBuilder.Entity("WebApplication1.Models.Maskine", b =>
                {
                    b.HasOne("WebApplication1.Models.Egenskab", "egenskab")
                        .WithMany()
                        .HasForeignKey("egenskabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("egenskab");
                });

            modelBuilder.Entity("WebApplication1.Models.Medarbejder", b =>
                {
                    b.HasOne("WebApplication1.Models.Modul", null)
                        .WithMany("medarbejdere")
                        .HasForeignKey("Modulid");
                });

            modelBuilder.Entity("WebApplication1.Models.Modul", b =>
                {
                    b.HasOne("WebApplication1.Models.Periode", "periode")
                        .WithMany("moduler")
                        .HasForeignKey("periodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("periode");
                });

            modelBuilder.Entity("WebApplication1.Models.Nedetid", b =>
                {
                    b.HasOne("WebApplication1.Models.Maskine", null)
                        .WithMany("nedetider")
                        .HasForeignKey("Maskineid");
                });

            modelBuilder.Entity("WebApplication1.Models.Rolle", b =>
                {
                    b.HasOne("WebApplication1.Models.Egenskab", "egenskab")
                        .WithMany()
                        .HasForeignKey("egenskabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Medarbejder", "medarbejder")
                        .WithMany()
                        .HasForeignKey("medarbejderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("egenskab");

                    b.Navigation("medarbejder");
                });

            modelBuilder.Entity("WebApplication1.Models.Maskine", b =>
                {
                    b.Navigation("nedetider");
                });

            modelBuilder.Entity("WebApplication1.Models.Modul", b =>
                {
                    b.Navigation("medarbejdere");
                });

            modelBuilder.Entity("WebApplication1.Models.Periode", b =>
                {
                    b.Navigation("moduler");
                });
#pragma warning restore 612, 618
        }
    }
}
