// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Egenskab", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RolleId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RolleId");

                    b.ToTable("Egenskab");
                });

            modelBuilder.Entity("WebApplication1.Models.Fravaer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MedarbejderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MedarbejderId");

                    b.ToTable("Fravaer");
                });

            modelBuilder.Entity("WebApplication1.Models.Maskine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EgenskabId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EgenskabId");

                    b.ToTable("Maskine");
                });

            modelBuilder.Entity("WebApplication1.Models.Medarbejder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ArbejdsdagSlut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ArbejdsdagStart")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ArbejdstimerOmUgen")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Farve")
                        .HasColumnType("longtext");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RealPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tlf")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Medarbejder");
                });

            modelBuilder.Entity("WebApplication1.Models.Modul", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MaskineId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MedarbejderId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MaskineId");

                    b.HasIndex("MedarbejderId");

                    b.ToTable("Modul");
                });

            modelBuilder.Entity("WebApplication1.Models.Nedetid", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Dag")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Gentagende")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaskineId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeOnly>("Tidspunkt")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("MaskineId");

                    b.ToTable("Nedetid");
                });

            modelBuilder.Entity("WebApplication1.Models.Rolle", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MedarbejderId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MedarbejderId");

                    b.ToTable("Rolle");
                });

            modelBuilder.Entity("WebApplication1.Models.Egenskab", b =>
                {
                    b.HasOne("WebApplication1.Models.Rolle", null)
                        .WithMany("Egenskaber")
                        .HasForeignKey("RolleId");
                });

            modelBuilder.Entity("WebApplication1.Models.Fravaer", b =>
                {
                    b.HasOne("WebApplication1.Models.Medarbejder", "Medarbejder")
                        .WithMany()
                        .HasForeignKey("MedarbejderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medarbejder");
                });

            modelBuilder.Entity("WebApplication1.Models.Maskine", b =>
                {
                    b.HasOne("WebApplication1.Models.Egenskab", "Egenskab")
                        .WithMany()
                        .HasForeignKey("EgenskabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Egenskab");
                });

            modelBuilder.Entity("WebApplication1.Models.Modul", b =>
                {
                    b.HasOne("WebApplication1.Models.Maskine", null)
                        .WithMany("Moduler")
                        .HasForeignKey("MaskineId");

                    b.HasOne("WebApplication1.Models.Medarbejder", "Medarbejder")
                        .WithMany()
                        .HasForeignKey("MedarbejderId");

                    b.Navigation("Medarbejder");
                });

            modelBuilder.Entity("WebApplication1.Models.Nedetid", b =>
                {
                    b.HasOne("WebApplication1.Models.Maskine", null)
                        .WithMany("Nedetider")
                        .HasForeignKey("MaskineId");
                });

            modelBuilder.Entity("WebApplication1.Models.Rolle", b =>
                {
                    b.HasOne("WebApplication1.Models.Medarbejder", null)
                        .WithMany("Roller")
                        .HasForeignKey("MedarbejderId");
                });

            modelBuilder.Entity("WebApplication1.Models.Maskine", b =>
                {
                    b.Navigation("Moduler");

                    b.Navigation("Nedetider");
                });

            modelBuilder.Entity("WebApplication1.Models.Medarbejder", b =>
                {
                    b.Navigation("Roller");
                });

            modelBuilder.Entity("WebApplication1.Models.Rolle", b =>
                {
                    b.Navigation("Egenskaber");
                });
#pragma warning restore 612, 618
        }
    }
}
